name: flutter_for_dev_dm
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  mockito: ^5.0.14
  faker: ^2.0.0
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/

